- name: playbook with deployment tasks
  hosts: lilbro
  gather_facts: no
  vars:
    path: /home/projects/
    use_docker: true
  tasks: 
    - name: clone repository
      git:
        repo: https://github.com/ArtgtH/fiber-postgres-docker.git
        dest: "{{ path }}"
        version: master
        update: yes
      tags: clone-repo
    
    - name: start container
      community.docker.docker_compose:
        project_src: "{{ path }}"
        build: yes
      when: use_docker
      tags: start-with-docker
    
    - name: make start
      command: make build
      args:
        chdir: "{{ path }}"
      when: not use_docker
      tags: start-with-make