---
- name: playbook with tasks to setup server
  hosts: lilbro
  gather_facts: no
  become: yes
  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes

  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes
      tags: install-git
          

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
      tags: install-docker


    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: install-docker


    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present
      tags: install-docker


    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
      tags: install-docker


    - name: Install docker-compose
      apt:
        name: docker-compose
        state: present
        update_cache: yes
      tags: install-docker-compose
  
   